language: php

sudo: false

services:
  - mysql

php:
  - 7.1
  - 7.2
  - nightly

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - SYMFONY_VERSION="^3.4"
  - COMPOSER_FLAGS=""

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony:"$SYMFONY_VERSION"; fi;
  - cp vendor/endroid/bundle-test/.env.travis vendor/endroid/bundle-test/.env.test

install:
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/simple-phpunit
  - vendor/endroid/bundle-test/bin/console server:run 0.0.0.0:9090 -q &
  - vendor/bin/behat

notifications:
  email: info@endroid.nl
