services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Endroid\Guide\Loader\LoaderInterface:
            tags: ['endroid_guide.loader']

    Endroid\Guide\Loader\:
        resource: '../../../vendor/endroid/guide/src/Loader/*'

    Endroid\GuideBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']

    Endroid\Guide\Guide:
        calls:
            - [addLoaders, [!tagged endroid_guide.loader]]
